### ISSUE TITLE
Use of STM32 Clones in new radios

### ISSUE THREAD

**Issue by luzemario** [LibreDMR/MDUV380_Testbed#1]
Maybe this can be useful:

[https://community.st.com/t5/stm32-mcus-products/how-to-spot-fake-stm32-mcu/td-p/147180](url)

Or this:

[https://github.com/keirf/Greaseweazle/wiki/STM32-Fakes](url)

Lastly, this:

[https://www.cnx-software.com/2020/03/22/how-to-detect-stm32-fakes/](url)

The use of a newer core, changed behavior or at last a bad program flow can be the cause for OpenGD77 having issues, I think.

**Comment by rogerclarkmelbourne** [comment]
We already found out the difference in these CPUs and developed a work-around.

This repo is no longer necessary and will be deleted soon.
